name: Bug Report
description: Report a problem with the software
labels: ["Bug Report"]
assignees:
  - kiwifruitdev
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help us reproduce and fix the bug as quickly as possible.
  - type: dropdown
    id: release
    attributes:
      label: Release
      description: Which release of the software are you using?
      options:
        - Steam Release
        - Pirated or Cracked
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: |
        Which version of the software are you using?
        This can be found in the bottom-left corner of the console window.
        Open the console window by pressing F5 on your keyboard.
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - Windows
        - SteamOS (Steam Deck)
        - Linux
        - macOS
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Please describe the severity of the bug.
      options:
        - Critical
        - Minor
        - Cosmetic
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the bug in as much detail as possible.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **The next section is optional, but its information can help us reproduce the bug more easily.**
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Please describe the steps to reproduce the bug.
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Please describe what you expected to happen.
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Please describe what actually happened.
  - type: markdown
    attributes:
      value: |
        **The next section is optional, but feel free to upload any relevant files.**
  - type: input
    id: log
    attributes:
      label: Console Log
      description: |
        Please upload the contents of console.txt to a pastebin service and paste the link here.
        This file is located in the same folder as the game executable.
  - type: input
    id: options
    attributes:
      label: Options Save File
      description: |
        Please upload the contents of Options.json to a pastebin service and paste the link here.
        This file is located in the same folder as the game executable.
  - type: input
    id: userconsents
    attributes:
      label: User Consents
      description: |
        Please upload the contents of UserConsents.json to a pastebin service and paste the link here.
        This file is located in the same folder as the game executable.
        It is only created when you subscribe to a Workshop effect that requires additional permissions.
  - type: input
    id: screenshots
    attributes:
      label: Screenshots
      description: Please upload any screenshots as an album to Imgur or a similar service and paste the link here.
  - type: markdown
    attributes:
      value: |
        **The next section is optional, but feel free to fill it out if you have any additional information.**
  - type: checkboxes
    id: proton
    attributes:
      label: Proton Version
      description: If using non-Windows, which Proton versions have you tried?
      options:
        - label:  Ge-Proton7-30
        - label: Proton Experimental
        - label: Proton 8.0-3
        - label: Proton 7.0-6
        - label: Proton 6.3-8
        - label: Proton 5.13-6
        - label: Proton 5.0-10
        - label: Proton 4.11-13
        - label: Proton 4.2-9
        - label: Proton 3.16-9
        - label: Proton 3.7-8
        - label: Proton Hotfix
  - type: input
    id: contact
    attributes:
      label: Contact
      description: |
        If you would like to be contacted about this bug privately, please enter your contact information here.
        Otherwise, leave this blank.